<?php
// $Id: jquery_impromptu.module,v 1.1.2.3 2008/12/09 12:07:49 obsidiandesign Exp $

/**
 * This module doesn't do too much, but it is a central location for any other
 * modules that implement the jQuery Impromptu library. It ensures that multiple
 * modules will all include the same library script just once on any given page.
 */

/**
 * Add the jQuery Impromptu javascript library to this page.
 */
function jquery_impromptu_add() {
  static $done;
  if (!isset($done)) {
    $path = drupal_get_path('module', 'jquery_impromptu');
    drupal_add_css($path .'/jquery_impromptu.css');
    drupal_add_js($path .'/jquery_impromptu.js');
    $done = TRUE;
  }
}