<?php

// $Id: referral_userpoints.module,v 1.1.2.2 2008/12/01 01:47:47 kbahey Exp $

define('REFERRAL_USERPOINTS', 'referral_userpoints');

/**
 * Implementation of hook_referral
 */
function referral_userpoints_referral($new_uid, $referring_uid) {
  userpoints_userpointsapi(array(
    'points'      => variable_get(REFERRAL_USERPOINTS, 0),
    'uid'         => $referring_uid,
    'operation'   => 'referral',
    'entity_id'   => $referring_uid,
    'entity_type' => 'user',
    'reference'   => 'referral'
    )
  );
}

/**
 * Implementation of hook_userpoints
 */
function referral_userpoints_userpoints($op, $points = 0, $uid = 0, $event = '') {
  if ($op == 'setting') {
    $group = 'referral';
    $form[$group] = array(
      '#type'          => 'fieldset',
      '#collapsible'   => TRUE,
      '#collapsed'     => TRUE,
      '#title'         => t('!Points for referral', userpoints_translation()),
    );

    $form[$group][REFERRAL_USERPOINTS] = array(
      '#type'          => 'textfield',
      '#title'         => t('!Points for referring a user', userpoints_translation()),
      '#default_value' => variable_get(REFERRAL_USERPOINTS, 0),
      '#size'          => 5,
      '#maxlength'     => 5,
    );
    return $form;
  }
}
