<?php


function addtoany_perm() {
  //$perms = array('administer content types', 'administer nodes', 'access content', 'view revisions', 'revert revisions');

  foreach (node_get_types() as $type) {
      $name = check_plain($type->type);
      $perms[] = 'share '. $name .' content';
    
  }

  return $perms;
}


function addtoany_link($type,$node=NULL, $teaser = FALSE) {
    global $base_url;
	if(variable_get('clean_url','0')==0)
		$link_url = $base_url.'/?q='.$_GET['q'];
	else
		$link_url = $base_url.'/'.$_GET['q'];
	
	$string = 'share '. $node->type .' content';
 	drupal_add_css((drupal_get_path('module', 'addtoany') .'/addtoany.css'), $type = 'module', $media = 'all', $preprocess = TRUE);
	$links = array();
        /*
	 $output .= '<a name="a2a_dd" onmouseover="a2a_show_dropdown(this)" onmouseout="a2a_onMouseOut_delay()" href="http://www.addtoany.com/bookmark?linkname='.rawurlencode($node->title).'&amp;linkurl='.rawurlencode($link_url).'">
					<img src="http://www.addtoany.com/bookmark.gif" width="91" height="16" border="0" alt="Bookmark"/></a>
					<script type="text/javascript">a2a_linkname="'.$node->title.'";a2a_linkurl="'.$link_url.'";</script>
					<script type="text/javascript" src="http://www.addtoany.com/js.dropdown.js?type=page"></script>';
         */
         $output .= file_get_contents(drupal_get_path('module', 'addtoany') .'/addtoany.js');
					
	if (!$teaser && user_access($string)) {
	    $links['addtoany'] = array(
		    'title' => '<div class="addtoany" style="display:inline">'.$output.'</div>',
		    'href' => '#',
			'html' => TRUE,
		  );
	}  
	return $links;

}

