<?php
// $Id: openflashchart.module,v 1.9 2008/07/07 13:14:36 brmassa Exp $
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Use Open Flash Chart on your site.
 *
 * @note only hooks are here.
 */

/**
 * Immplementation of hook_charts_info().
 *
 * Its a Charts module hook. It defines almost all aspects
 * of a chart provider, like its name, what types of charts
 * it can perform and what are the restrictions.
 */
function openflashchart_charts_info() {
  return array(
    'openflashchart' => array(
      'file'    => drupal_get_path('module', 'openflashchart') .'/openflashchart.inc',
      'name'    => t('Open Flash Chart'),
      'render'  => '_openflashchart_charts_render',
      'types'   => array(
        'line2D'  => t('Line 2D'),
        'vbar2D'  => t('Vertical Bar 2D'),
        'vbar3D'  => t('Vertical Bar 3D'),
        'pie2D'   => t('Pie 2D'),
      ),
    ),
  );
}
