<?php
/*
 * Drupal Module: Christmas Snow
 * Adds Christmas Snow to your site
 
 *
 * @author: introfini <www.josefernandes.pt>
 */

function christmas_snow_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Add Christmas Snow to your site.');
    case 'admin/settings/christmas_snow':
      return t('Add Christmas Snow to your site.');
  }
}

function christmas_snow_init() {
  $path = drupal_get_path('module', 'christmas_snow');
  $js = drupal_add_js($path . '/script/snowstorm.js');
  $data = '<script type="text/javascript">var imagePath = "'.$GLOBALS['base_url'].'/'.$path.'/image/snow/";</script>';
  drupal_set_html_head($data); 
}
