<?php
// $Id: l10n_localpacks.install,v 1.1.2.2 2007/12/17 20:09:54 goba Exp $
/**
 * @file
 *   Localization community for local packages, update and uninstallation.
 */

/**
 * Implementation of hook_uninstall().
 */
function l10n_localpacks_uninstall() {
  variable_del('l10n_localpacks_directory');
  variable_del('l10n_localpacks_cron');
  variable_del('l10n_localpacks_limit');
  variable_del('l10n_localpacks_home_link');
}
