<?php
// $Id: stormorganization.module,v 1.11.4.20 2009/01/06 15:16:22 robertogerola Exp $

/**
 * @file
 */

function stormorganization_help($path, $arg) {
  $output = '';

  switch ($path) {
    case "admin/help#stormorganization":
      $output = '<p>'. storm_t("Provides organization support for Storm", 'organization') .'</p>';
      break;
  }

  return $output;
}

function stormorganization_perm() {
  return array(
                'Storm organization: access',
                'Storm organization: add',
                'Storm organization: delete all',
                'Storm organization: delete own',
                'Storm organization: edit all',
                'Storm organization: edit own',
                'Storm organization: edit belonged',
                'Storm organization: view all',
                'Storm organization: view own',
                'Storm organization: view belonged',
                'Storm organization: associate user'
              );
}

function stormorganization_access($op, $node, $account = NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  if (is_numeric($node)) $node = node_load($node);

  if ($op == 'create') {
    return user_access('Storm organization: add');
  }

  if ($op == 'delete') {
    if (user_access('Storm organization: delete all')) {
      return TRUE;
    }
    else if (user_access('Storm organization: delete own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }

  if ($op == 'update') {
    if (user_access('Storm organization: edit all')) {
      return TRUE;
    }
    else if (user_access('Storm organization: edit own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    else if (user_access('Storm organization: edit belonged') && ($account->stormorganization_nid == $node->nid)) {
      return TRUE;
    }
  }

  if ($op == 'view') {
    if (user_access('Storm organization: view all')) {
      return TRUE;
    }
    else if (user_access('Storm organization: view own') && ($account->uid == $node->uid)) {
      return TRUE;
    }
    else if (user_access('Storm organization: view belonged') && ($account->stormorganization_nid == $node->nid)) {
      return TRUE;
    }
  }
  return FALSE;
}

function stormorganization_access_sql($sql, $where = array()) {
  if (user_access('Storm organization: view all')) {
    $where[] = "'storm_access'='storm_access'";
    return storm_rewrite_sql($sql, $where);
  }

  global $user;

  $cond = '';
  if (user_access('Storm organization: view own')) {
    $cond .= 'n.uid='. $user->uid;
  }
  if (user_access('Storm organization: view belonged')) {
    if (!empty($cond)) $cond .= ' OR ';
    $cond .= 'n.nid='. $user->stormorganization_nid;
  }
  if (empty($cond)) $cond = '0=1';
  $where[] = $cond;

  $where[] = "'storm_access'='storm_access'";
  return storm_rewrite_sql($sql, $where);
}

function stormorganization_storm_rewrite_where_sql($query, $primary_table, $account) {
  static $conds = array();

  if ($conds[$account->uid]) {
    return $conds[$account->uid];
  }

  if (preg_match("/'storm_access'='storm_access'/", $query)) {
    $cond = '';
  }
  else {
    if (user_access('Storm organization: view all', $account)) {
      return '';
    }

    $cond = '';
    if (user_access('Storm organization: view own', $account)) {
      $cond .= "${primary_table}.uid=". $account->uid;
    }
    if (user_access('Storm organization: view belonged', $account)) {
      if ($cond) $cond .= ' OR ';
      $cond .= ' sor1.nid='. $account->stormorganization_nid;
    }
    if ($cond) {
      $cond = " WHEN 'stormorganization' THEN (SELECT IF($cond,1,0) FROM {stormorganization} sor1 WHERE sor1.vid=${primary_table}.vid) ";
    }
    else {
      $cond = " WHEN 'stormorganization' THEN 0 ";
    }
  }

  $conds[$account->uid] = $cond;
  return $cond;
}

function stormorganization_menu() {
  $items = array();
  $items['storm/organizations'] = array(
    'title' => storm_t('Organizations', 'organization'),
    'description' => storm_t('Storm Organizations', 'organization'),
    'page callback' => 'stormorganization_list',
    'access arguments' => array('Storm organization: access'),
    'file' => 'stormorganization.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  $items['storm/organizations/autocomplete'] = array(
    'title' => 'Organization autocomplete',
    'page callback' => 'stormorganization_autocomplete',
    'access arguments' => array('Storm organization: access'),
    'type' => MENU_CALLBACK,
    'file' => 'stormorganization.admin.inc',
  );
  return $items;
}

function stormorganization_theme() {
  return array(
    'stormorganization_list' => array(
      'file'      => 'stormorganization.theme.inc',
      'arguments' => array('header', 'organizations'),
    ),
    'stormorganization_view' => array(
      'file'      => 'stormorganization.theme.inc',
      'arguments' => array('node', 'teaser', 'page'),
    ),
  );
}

function stormorganization_node_info() {
  return array(
    'stormorganization' => array(
      'name' => storm_t('Organization', 'organization'),
      'module' => 'stormorganization',
      'description' => storm_t("An organization for Storm.", 'organization'),
      'title_label' => storm_t("Name", 'organization'),
      'body_label' => storm_t("Note", 'organization'),
    )
  );
}

function stormorganization_form(&$node) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Storm'), 'storm');
  $breadcrumb[] = l(t('Organizations'), 'storm/organizations');
  drupal_set_breadcrumb($breadcrumb);

  $type = node_get_types('type', $node);

  $form['#attributes']['class'] = 'stormcomponent_node_form';

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -51,
  );

  $form['group0'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -50,
  );

  $form['group0']['iscustomer'] = array(
    '#type' => 'checkbox',
    '#title' => storm_t('Customer', 'organization'),
    '#default_value' => $node->iscustomer,
  );

  $form['group0']['isprovider'] = array(
    '#type' => 'checkbox',
    '#title' => storm_t('Provider', 'organization'),
    '#default_value' => $node->isprovider,
  );

  $form['group0']['isactive'] = array(
    '#type' => 'checkbox',
    '#title' => storm_t('Active', 'organization'),
    '#default_value' => $node->isactive,
  );

  $form['group1'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -49,
  );

  $form['group1']['prefix'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Prefix', 'organization'),
    '#size' => 20,
    '#default_value' => $node->prefix,
  );

  $form['group1']['fullname'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Fullname', 'organization'),
    '#size' => 40,
    '#default_value' => $node->fullname,
  );

  $form['group2'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -48,
  );

  $form['group2']['country'] = array(
    '#type' => 'select',
    '#title' => storm_t('Country', 'organization'),
    '#options' => stormattribute_attributes_bydomain('Country'),
    '#default_value' => $node->country,
  );

  $form['group2']['provstate'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Province / State', 'organization'),
    '#size' => 20,
    '#default_value' => $node->provstate,
  );

  $form['group2']['city'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('City', 'organization'),
    '#size' => 20,
    '#default_value' => $node->city,
  );

  $form['group3'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -47,
  );

  $form['group3']['zip'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Zip', 'organization'),
    '#size' => 15,
    '#default_value' => $node->zip,
  );

  $form['group3']['address'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Address', 'organization'),
    '#default_value' => $node->address,
  );

  $form['group4'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -46,
  );

  $form['group4']['currency'] = array(
    '#type' => 'select',
    '#title' => storm_t('Currency', 'organization'),
    '#options' => stormattribute_attributes_bydomain('Currency'),
    '#default_value' => $node->currency,
  );

  $languages = language_list('language', TRUE);
  $languages_options = array();
  foreach ($languages as $language_code => $language) {
    $languages_options[$language_code] = $language->name;
  }
  $form['group4']['orglanguage'] = array(
    '#type' => 'select',
    '#title' => storm_t('Language', 'organization'),
    '#options' => $languages_options,
    '#default_value' => $node->orglanguage,
  );

  $form['group4']['taxid'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Tax ID', 'organization'),
    '#size' => 20,
    '#default_value' => $node->taxid,
  );

  $form['group5'] = array(
    '#type' => 'markup',
    '#theme' => 'storm_form_group',
    '#weight' => -45,
  );

  $form['group5']['www'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('WWW', 'organization'),
    '#size' => 30,
    '#default_value' => $node->www,
  );

  $form['group5']['email'] = array(
    '#type' => 'textfield',
    '#title' => storm_t('Email', 'organization'),
    '#size' => 30,
    '#default_value' => $node->email,
  );

  if ($type->has_body) {
    $form['body_filter']['#weight'] = -44;
    $form['body_filter']['body'] = array(
      '#type' => 'textarea',
      '#title' => check_plain($type->body_label),
      '#default_value' => $node->body,
      '#required' => FALSE
    );
    $form['body_filter']['format'] = filter_form($node->format);
  }

  $form['title_old'] = array(
    '#type' => 'hidden',
    '#default_value' => $node->title_old,
  );

  return $form;
}

function stormorganization_insert($node) {
  db_query("INSERT INTO {stormorganization}
           (vid, nid, prefix, fullname, country, www, email, currency,
           provstate, zip, city, address, taxid, orglanguage, iscustomer, isprovider, isactive
           ) VALUES
           (%d, %d, '%s', '%s', '%s', '%s', '%s', '%s',
           '%s', '%s', '%s', '%s', '%s', '%s', %d, %d, %d
           )",
            $node->vid, $node->nid, $node->prefix, $node->fullname, $node->country, $node->www, $node->email, $node->currency,
            $node->provstate, $node->zip, $node->city, $node->address, $node->taxid, 
            $node->orglanguage, $node->iscustomer, $node->isprovider, $node->isactive
            );
}

function stormorganization_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    stormorganization_insert($node);
  }
  else {
    db_query("UPDATE {stormorganization} SET
              prefix = '%s', fullname = '%s', country='%s', www='%s', email='%s', currency = '%s',
              provstate = '%s', zip = '%s', city = '%s', address = '%s', taxid = '%s', orglanguage = '%s',
              iscustomer=%d, isprovider=%d, isactive=%d WHERE vid = %d",
              $node->prefix, $node->fullname, $node->country, $node->www, $node->email, $node->currency,
              $node->provstate, $node->zip, $node->city, $node->address, $node->taxid, $node->orglanguage,
              $node->iscustomer, $node->isprovider, $node->isactive, $node->vid);
    if ($node->title != $node->title_old) {
      module_invoke_all('stormorganization_change', $node->nid, $node->title);
    }
  }
}

function stormorganization_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'prepare':
      if(!$node->nid) {
        $node->iscustomer = 1;
        $node->isactive = 1;
      }
      break;
    case 'delete revision':
      // Notice that we're matching a single revision based on the node's vid.
      db_query('DELETE FROM {stormorganization} WHERE vid = %d', $node->vid);
      break;
  }
}

function stormorganization_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_query('DELETE FROM {stormorganization} WHERE nid = %d', $node->nid);
}

function stormorganization_load($node) {
  $additions = db_fetch_object(db_query('SELECT * FROM {stormorganization} WHERE vid = %d', $node->vid));
  $additions->title_old = $node->title;
  return $additions;
}

function stormorganization_view($node, $teaser = FALSE, $page = FALSE) {
  $breadcrumb = array();
  $breadcrumb[] = l(t('Storm'), 'storm');
  $breadcrumb[] = l(t('Organizations'), 'storm/organizations');
  drupal_set_breadcrumb($breadcrumb);

  return theme('stormorganization_view', $node, $teaser, $page);
}

function stormorganization_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'storm_admin_settings') {
    $s = "SELECT n.nid, n.title FROM  {node} AS n INNER JOIN {stormorganization} AS sor ON sor.nid=n.nid WHERE n.status=1 AND n.type='stormorganization' ORDER BY n.title";
    $s = stormorganization_access_sql($s);
    $s = db_rewrite_sql($s);
    $r = db_query($s);
    $organizations = array();
    while ($organization = db_fetch_object($r)) {
      $organizations[$organization->nid] = $organization->title;
    }
    $form['storm_organization_nid'] = array(
      '#type' => 'select',
      '#title' => storm_t('Organization', 'organization'),
      '#options' => $organizations,
      '#default_value' => variable_get('storm_organization_nid', 0),
      '#description' => storm_t('The organization that owns this system', 'organization'),
      '#weight' => -30,
    );
  }
}

