<?php
/**
 * Implementation of hook_uauto_isearch().
 */ 
function uauto_dirSearch_uauto_isearch($keytext = null, &$find) { 
  uauto_dirSearch_uauto_ksearch($keytext, $find);
}
/**
 * Implementation of hook_uauto_ksearch().
 */
function uauto_dirSearch_uauto_ksearch($keytext = null, &$find) { 
  $limit = variable_get('uauto_d_no_results', 25);
   // dirseach is limited to directories only
  if(!(is_dir($keytext) && variable_get('uauto_d_enable', 1) && array_shift(explode('/', $keytext)) ==='files'))
    return;
  else {    
      $regex = ".*";
      $ignore_paths = array('.', '..', 'CVS');
      $recurse = TRUE;       
      $files = file_scan_directory($keytext, $regex, $ignore_paths, NULL, $recurse);
      foreach ($files as $file) {     
        if($limit-- < 0)
            break;      
        $find["$file->filename"] = array_pop(explode('/', $file->filename));;
      }
  }
}   
    
/**
 * Implementation of hook_ulink_general_settings().
 */
function uauto_dirSearch_ulink_general_settings() {
  $form['dir_search']= array(
    '#type' => 'fieldset',
    '#title' => t('dsearch'),
    '#collapsible' => FALSE,
    '#description' => t('Directory search settings'),
  );  
  $form['dir_search']['uauto_d_enable']= array(
    '#type' => 'checkbox',
    '#title' => t('Enable dsearch'),
    '#default_value' => variable_get('uauto_d_enable', 1),
  ); 
  $form['dir_search']['uauto_d_no_results']= array(
    '#type' => 'textfield',
    '#title' => t('Limit search results to'),
    '#size' => 3,
    '#maxlength' => 4, 
    '#default_value' => variable_get('uauto_d_no_results', 25),
    '#description' => t('Number of maximum entries to be searched for and displayed.'),
  ); 
  return $form;
}
